services:
  backend:
    build:
      target: dev
    working_dir: /app
    command: ["sh", "-c", "./scripts/dev_entrypoint.sh"]
    environment:
      - AUTO_MIGRATE=true
      - WAIT_FOR_EMBEDDING=true
    volumes:
      # Mount only source directories to preserve image's virtualenv
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
      - ./backend/scripts:/app/scripts
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/uv.lock:/app/uv.lock
    networks:
      - web
      - bridge

  embedding-service:
    networks:
      - bridge
    volumes:
      # Mount source for hot reload
      - ./embedding-service/app:/app/app
      - ./embedding-service/pyproject.toml:/app/pyproject.toml
    command: ["uv", "run", "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8001"]

  frontend:
    build:
      target: dev
    command: ["pnpm", "dev", "--host", "0.0.0.0", "--port", "3000"]
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # for HMR while keeping installed deps from the image
      - ./frontend/app:/app/app
      - ./frontend/lib:/app/lib
      - ./frontend/public:/app/public
      - ./frontend/server:/app/server
      - ./frontend/nuxt.config.ts:/app/nuxt.config.ts
      - ./frontend/package.json:/app/package.json
      - ./frontend/pnpm-lock.yaml:/app/pnpm-lock.yaml
    networks:
      - web
      - bridge

  postgres-test:
    image: pgvector/pgvector:pg18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_test
    ports:
      - "54323:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pg-test-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg-test-data: