/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ClaimUpdateText } from './claimUpdateText';
import type { ClaimUpdateClaimType } from './claimUpdateClaimType';
import type { ClaimUpdatePageNumber } from './claimUpdatePageNumber';
import type { ClaimUpdateParagraphIndex } from './claimUpdateParagraphIndex';
import type { ClaimUpdateVerificationStatus } from './claimUpdateVerificationStatus';

/**
 * Schema for updating a claim
 */
export interface ClaimUpdate {
  text?: ClaimUpdateText;
  claim_type?: ClaimUpdateClaimType;
  page_number?: ClaimUpdatePageNumber;
  paragraph_index?: ClaimUpdateParagraphIndex;
  verification_status?: ClaimUpdateVerificationStatus;
}
