/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ClaimCreateClaimType } from './claimCreateClaimType';
import type { ClaimCreatePageNumber } from './claimCreatePageNumber';
import type { ClaimCreateParagraphIndex } from './claimCreateParagraphIndex';

/**
 * Schema for creating a claim
 */
export interface ClaimCreate {
  text: string;
  claim_type?: ClaimCreateClaimType;
  page_number?: ClaimCreatePageNumber;
  paragraph_index?: ClaimCreateParagraphIndex;
  project_id: number;
  reference_ids?: number[];
}
