/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ClaimWithReferencesClaimType } from './claimWithReferencesClaimType';
import type { ClaimWithReferencesPageNumber } from './claimWithReferencesPageNumber';
import type { ClaimWithReferencesParagraphIndex } from './claimWithReferencesParagraphIndex';
import type { ReferenceOut } from './referenceOut';

/**
 * Schema for claim with full reference details
 */
export interface ClaimWithReferences {
  text: string;
  claim_type?: ClaimWithReferencesClaimType;
  page_number?: ClaimWithReferencesPageNumber;
  paragraph_index?: ClaimWithReferencesParagraphIndex;
  id: number;
  project_id: number;
  verification_status: string;
  created_at: string;
  updated_at: string;
  references?: number[];
  reference_details?: ReferenceOut[];
}
