/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ClaimOutClaimType } from './claimOutClaimType';
import type { ClaimOutPageNumber } from './claimOutPageNumber';
import type { ClaimOutParagraphIndex } from './claimOutParagraphIndex';

/**
 * Schema for claim output
 */
export interface ClaimOut {
  text: string;
  claim_type?: ClaimOutClaimType;
  page_number?: ClaimOutPageNumber;
  paragraph_index?: ClaimOutParagraphIndex;
  id: number;
  project_id: number;
  verification_status: string;
  created_at: string;
  updated_at: string;
  references?: number[];
}
