/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { DoclingPDFToMarkdownResponseDocumentTitle } from './doclingPDFToMarkdownResponseDocumentTitle';
import type { DoclingPDFToMarkdownResponsePageCount } from './doclingPDFToMarkdownResponsePageCount';

/**
 * Schema for PDF to Markdown conversion response.
 */
export interface DoclingPDFToMarkdownResponse {
  project_id: number;
  document_id: number;
  filename: string;
  document_title: DoclingPDFToMarkdownResponseDocumentTitle;
  markdown: string;
  page_count: DoclingPDFToMarkdownResponsePageCount;
}
