/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentOutDocumentTitle } from './documentOutDocumentTitle';
import type { DocumentOutPageCount } from './documentOutPageCount';

export interface DocumentOut {
  filename: string;
  document_title?: DocumentOutDocumentTitle;
  markdown_content: string;
  page_count?: DocumentOutPageCount;
  id: number;
  project_id: number;
  created_at: string;
  updated_at: string;
}
