/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ExtractedReferenceYear } from './extractedReferenceYear';
import type { ExtractedReferenceSource } from './extractedReferenceSource';
import type { ExtractedReferenceDoi } from './extractedReferenceDoi';
import type { ExtractedReferenceUrl } from './extractedReferenceUrl';

/**
 * Schema for an extracted reference from text.
 */
export interface ExtractedReference {
  /** Title of the reference */
  title: string;
  /** Authors of the reference (comma-separated or formatted) */
  authors: string;
  /** Publication year */
  year?: ExtractedReferenceYear;
  /** Source (journal, conference, book, etc.) */
  source?: ExtractedReferenceSource;
  /** DOI if available */
  doi?: ExtractedReferenceDoi;
  /** URL if available */
  url?: ExtractedReferenceUrl;
}
