/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ExtractedClaim } from './extractedClaim';
import type { ExtractedReference } from './extractedReference';

/**
 * Schema for the complete extraction result.
 */
export interface ExtractionResult {
  /** Extracted claims */
  claims?: ExtractedClaim[];
  /** Extracted references */
  references?: ExtractedReference[];
}
