/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ExtractedClaimClaimType } from './extractedClaimClaimType';
import type { ExtractedClaimPageNumber } from './extractedClaimPageNumber';
import type { ExtractedClaimParagraphIndex } from './extractedClaimParagraphIndex';

/**
 * Schema for an extracted claim from text.
 */
export interface ExtractedClaim {
  /** The claim text */
  text: string;
  /** Type of claim (factual, statistical, opinion, etc.) */
  claim_type?: ExtractedClaimClaimType;
  /** Page number where claim appears */
  page_number?: ExtractedClaimPageNumber;
  /** Paragraph index */
  paragraph_index?: ExtractedClaimParagraphIndex;
  /** Indices of references that support this claim (0-based index into the references list) */
  reference_indices?: number[];
}
