/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */

export type LinkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostParams = {
relevance_score?: number | null;
context?: string | null;
};
