/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectOutDescription } from './projectOutDescription';
import type { ProjectOutStatus } from './projectOutStatus';
import type { ProjectOutDocumentPath } from './projectOutDocumentPath';
import type { ProjectOutDocumentFilename } from './projectOutDocumentFilename';

export interface ProjectOut {
  name: string;
  description?: ProjectOutDescription;
  status?: ProjectOutStatus;
  id: number;
  document_path?: ProjectOutDocumentPath;
  document_filename?: ProjectOutDocumentFilename;
  created_at: string;
  updated_at: string;
}
