/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectUpdateName } from './projectUpdateName';
import type { ProjectUpdateDescription } from './projectUpdateDescription';
import type { ProjectUpdateStatus } from './projectUpdateStatus';

export interface ProjectUpdate {
  name?: ProjectUpdateName;
  description?: ProjectUpdateDescription;
  status?: ProjectUpdateStatus;
}
