/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for references-only extraction request.
 */
export interface ReferencesExtractionRequest {
  /** Text to extract references from */
  text: string;
  /** Project ID to associate the extracted references with */
  project_id: number;
}
