/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ExtractedReference } from './extractedReference';

/**
 * Schema for references-only extraction response.
 */
export interface ReferencesExtractionResponse {
  project_id: number;
  references: ExtractedReference[];
  references_created: number;
  references_deduplicated: number;
}
