/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ReferenceCreateDoi } from './referenceCreateDoi';
import type { ReferenceCreateSource } from './referenceCreateSource';
import type { ReferenceCreateYear } from './referenceCreateYear';
import type { ReferenceCreateUrl } from './referenceCreateUrl';

/**
 * Schema for creating a reference
 */
export interface ReferenceCreate {
  doi?: ReferenceCreateDoi;
  title: string;
  authors: string;
  source?: ReferenceCreateSource;
  year?: ReferenceCreateYear;
  url?: ReferenceCreateUrl;
}
