/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ReferenceOutDoi } from './referenceOutDoi';
import type { ReferenceOutSource } from './referenceOutSource';
import type { ReferenceOutYear } from './referenceOutYear';
import type { ReferenceOutUrl } from './referenceOutUrl';

/**
 * Schema for reference output
 */
export interface ReferenceOut {
  doi?: ReferenceOutDoi;
  title: string;
  authors: string;
  source?: ReferenceOutSource;
  year?: ReferenceOutYear;
  url?: ReferenceOutUrl;
  id: number;
  dedup_hash: string;
  is_processed: boolean;
  created_at: string;
  updated_at: string;
}
