/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ReferenceUpdateDoi } from './referenceUpdateDoi';
import type { ReferenceUpdateTitle } from './referenceUpdateTitle';
import type { ReferenceUpdateAuthors } from './referenceUpdateAuthors';
import type { ReferenceUpdateSource } from './referenceUpdateSource';
import type { ReferenceUpdateYear } from './referenceUpdateYear';
import type { ReferenceUpdateUrl } from './referenceUpdateUrl';
import type { ReferenceUpdateIsProcessed } from './referenceUpdateIsProcessed';

/**
 * Schema for updating a reference
 */
export interface ReferenceUpdate {
  doi?: ReferenceUpdateDoi;
  title?: ReferenceUpdateTitle;
  authors?: ReferenceUpdateAuthors;
  source?: ReferenceUpdateSource;
  year?: ReferenceUpdateYear;
  url?: ReferenceUpdateUrl;
  is_processed?: ReferenceUpdateIsProcessed;
}
