/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import type { ExtractionResult } from './extractionResult';

/**
 * Schema for text extraction response.
 */
export interface TextExtractionResponse {
  project_id: number;
  extraction_result: ExtractionResult;
  claims_created: number;
  references_created: number;
  references_deduplicated: number;
}
