/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for text extraction request.
 */
export interface TextExtractionRequest {
  /** Text to extract claims and references from */
  text: string;
  /** Project ID to associate the extracted claims with */
  project_id: number;
}
