/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  ClaimCreate,
  ClaimOut,
  ClaimUpdate,
  ClaimWithReferences,
  HTTPValidationError,
  LinkClaimToReferenceParams,
  ListClaimsParams,
  PaginatedResponseClaimOut
} from '../models';






/**
 * List claims with optional filtering by project.
 * @summary List Claims
 */
export const listClaims = (
    params?: MaybeRef<ListClaimsParams>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedResponseClaimOut>> => {
    params = unref(params);
    
    return axios.default.get(
      `/api/v1/claims/`,{
    ...options,
        params: {...unref(params), ...options?.params},}
    );
  }




export const getListClaimsQueryKey = (params?: MaybeRef<ListClaimsParams>,) => {
    return [
    'api','v1','claims', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListClaimsQueryOptions = <TData = Awaited<ReturnType<typeof listClaims>>, TError = AxiosError<HTTPValidationError>>(params?: MaybeRef<ListClaimsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaims>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getListClaimsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listClaims>>> = ({ signal }) => listClaims(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listClaims>>, TError, TData> 
}

export type ListClaimsQueryResult = NonNullable<Awaited<ReturnType<typeof listClaims>>>
export type ListClaimsQueryError = AxiosError<HTTPValidationError>


/**
 * @summary List Claims
 */

export function useListClaims<TData = Awaited<ReturnType<typeof listClaims>>, TError = AxiosError<HTTPValidationError>>(
 params?: MaybeRef<ListClaimsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaims>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListClaimsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




/**
 * Create a new claim and optionally link it to references.
 * @summary Create Claim
 */
export const createClaim = (
    claimCreate: MaybeRef<ClaimCreate>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ClaimOut>> => {
    claimCreate = unref(claimCreate);
    
    return axios.default.post(
      `/api/v1/claims/`,
      claimCreate,options
    );
  }



export const getCreateClaimMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createClaim>>, TError,{data: ClaimCreate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createClaim>>, TError,{data: ClaimCreate}, TContext> => {

const mutationKey = ['createClaim'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createClaim>>, {data: ClaimCreate}> = (props) => {
          const {data} = props ?? {};

          return  createClaim(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateClaimMutationResult = NonNullable<Awaited<ReturnType<typeof createClaim>>>
    export type CreateClaimMutationBody = ClaimCreate
    export type CreateClaimMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Create Claim
 */
export const useCreateClaim = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createClaim>>, TError,{data: ClaimCreate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createClaim>>,
        TError,
        {data: ClaimCreate},
        TContext
      > => {

      const mutationOptions = getCreateClaimMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get a claim with full reference details.
 * @summary Get Claim
 */
export const getClaim = (
    claimId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ClaimWithReferences>> => {
    claimId = unref(claimId);
    
    return axios.default.get(
      `/api/v1/claims/${claimId}`,options
    );
  }




export const getGetClaimQueryKey = (claimId?: MaybeRef<number>,) => {
    return [
    'api','v1','claims',claimId
    ] as const;
    }

    
export const getGetClaimQueryOptions = <TData = Awaited<ReturnType<typeof getClaim>>, TError = AxiosError<HTTPValidationError>>(claimId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClaim>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getGetClaimQueryKey(claimId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClaim>>> = ({ signal }) => getClaim(claimId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(claimId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClaim>>, TError, TData> 
}

export type GetClaimQueryResult = NonNullable<Awaited<ReturnType<typeof getClaim>>>
export type GetClaimQueryError = AxiosError<HTTPValidationError>


/**
 * @summary Get Claim
 */

export function useGetClaim<TData = Awaited<ReturnType<typeof getClaim>>, TError = AxiosError<HTTPValidationError>>(
 claimId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClaim>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetClaimQueryOptions(claimId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




/**
 * Update a claim.
 * @summary Update Claim
 */
export const updateClaim = (
    claimId: MaybeRef<number>,
    claimUpdate: MaybeRef<ClaimUpdate>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ClaimOut>> => {
    claimId = unref(claimId);
claimUpdate = unref(claimUpdate);
    
    return axios.default.put(
      `/api/v1/claims/${claimId}`,
      claimUpdate,options
    );
  }



export const getUpdateClaimMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateClaim>>, TError,{claimId: number;data: ClaimUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateClaim>>, TError,{claimId: number;data: ClaimUpdate}, TContext> => {

const mutationKey = ['updateClaim'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateClaim>>, {claimId: number;data: ClaimUpdate}> = (props) => {
          const {claimId,data} = props ?? {};

          return  updateClaim(claimId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateClaimMutationResult = NonNullable<Awaited<ReturnType<typeof updateClaim>>>
    export type UpdateClaimMutationBody = ClaimUpdate
    export type UpdateClaimMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Update Claim
 */
export const useUpdateClaim = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateClaim>>, TError,{claimId: number;data: ClaimUpdate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateClaim>>,
        TError,
        {claimId: number;data: ClaimUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateClaimMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a claim.
 * @summary Delete Claim
 */
export const deleteClaim = (
    claimId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    claimId = unref(claimId);
    
    return axios.default.delete(
      `/api/v1/claims/${claimId}`,options
    );
  }



export const getDeleteClaimMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteClaim>>, TError,{claimId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteClaim>>, TError,{claimId: number}, TContext> => {

const mutationKey = ['deleteClaim'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteClaim>>, {claimId: number}> = (props) => {
          const {claimId} = props ?? {};

          return  deleteClaim(claimId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteClaimMutationResult = NonNullable<Awaited<ReturnType<typeof deleteClaim>>>
    
    export type DeleteClaimMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Delete Claim
 */
export const useDeleteClaim = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteClaim>>, TError,{claimId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteClaim>>,
        TError,
        {claimId: number},
        TContext
      > => {

      const mutationOptions = getDeleteClaimMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Link a claim to a reference.
 * @summary Link Claim To Reference
 */
export const linkClaimToReference = (
    claimId: MaybeRef<number>,
    referenceId: MaybeRef<number>,
    params?: MaybeRef<LinkClaimToReferenceParams>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ClaimOut>> => {
    claimId = unref(claimId);
referenceId = unref(referenceId);
params = unref(params);
    
    return axios.default.post(
      `/api/v1/claims/${claimId}/references/${referenceId}`,undefined,{
    ...options,
        params: {...unref(params), ...options?.params},}
    );
  }



export const getLinkClaimToReferenceMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkClaimToReference>>, TError,{claimId: number;referenceId: number;params?: LinkClaimToReferenceParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof linkClaimToReference>>, TError,{claimId: number;referenceId: number;params?: LinkClaimToReferenceParams}, TContext> => {

const mutationKey = ['linkClaimToReference'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof linkClaimToReference>>, {claimId: number;referenceId: number;params?: LinkClaimToReferenceParams}> = (props) => {
          const {claimId,referenceId,params} = props ?? {};

          return  linkClaimToReference(claimId,referenceId,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LinkClaimToReferenceMutationResult = NonNullable<Awaited<ReturnType<typeof linkClaimToReference>>>
    
    export type LinkClaimToReferenceMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Link Claim To Reference
 */
export const useLinkClaimToReference = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkClaimToReference>>, TError,{claimId: number;referenceId: number;params?: LinkClaimToReferenceParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof linkClaimToReference>>,
        TError,
        {claimId: number;referenceId: number;params?: LinkClaimToReferenceParams},
        TContext
      > => {

      const mutationOptions = getLinkClaimToReferenceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Unlink a claim from a reference.
 * @summary Unlink Claim From Reference
 */
export const unlinkClaimFromReference = (
    claimId: MaybeRef<number>,
    referenceId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    claimId = unref(claimId);
referenceId = unref(referenceId);
    
    return axios.default.delete(
      `/api/v1/claims/${claimId}/references/${referenceId}`,options
    );
  }



export const getUnlinkClaimFromReferenceMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlinkClaimFromReference>>, TError,{claimId: number;referenceId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof unlinkClaimFromReference>>, TError,{claimId: number;referenceId: number}, TContext> => {

const mutationKey = ['unlinkClaimFromReference'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unlinkClaimFromReference>>, {claimId: number;referenceId: number}> = (props) => {
          const {claimId,referenceId} = props ?? {};

          return  unlinkClaimFromReference(claimId,referenceId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnlinkClaimFromReferenceMutationResult = NonNullable<Awaited<ReturnType<typeof unlinkClaimFromReference>>>
    
    export type UnlinkClaimFromReferenceMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Unlink Claim From Reference
 */
export const useUnlinkClaimFromReference = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlinkClaimFromReference>>, TError,{claimId: number;referenceId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof unlinkClaimFromReference>>,
        TError,
        {claimId: number;referenceId: number},
        TContext
      > => {

      const mutationOptions = getUnlinkClaimFromReferenceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    