/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  ClaimCreate,
  ClaimOut,
  ClaimUpdate,
  ClaimWithReferences,
  HTTPValidationError,
  LinkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostParams,
  ListClaimsApiV1ClaimsGetParams,
  PaginatedResponseClaimOut
} from '../models';






/**
 * List claims with optional filtering by project.
 * @summary List Claims
 */
export const listClaimsApiV1ClaimsGet = (
    params?: MaybeRef<ListClaimsApiV1ClaimsGetParams>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedResponseClaimOut>> => {
    params = unref(params);
    
    return axios.default.get(
      `/api/v1/claims/`,{
    ...options,
        params: {...unref(params), ...options?.params},}
    );
  }




export const getListClaimsApiV1ClaimsGetQueryKey = (params?: MaybeRef<ListClaimsApiV1ClaimsGetParams>,) => {
    return [
    'api','v1','claims', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListClaimsApiV1ClaimsGetQueryOptions = <TData = Awaited<ReturnType<typeof listClaimsApiV1ClaimsGet>>, TError = AxiosError<HTTPValidationError>>(params?: MaybeRef<ListClaimsApiV1ClaimsGetParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaimsApiV1ClaimsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getListClaimsApiV1ClaimsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listClaimsApiV1ClaimsGet>>> = ({ signal }) => listClaimsApiV1ClaimsGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listClaimsApiV1ClaimsGet>>, TError, TData> 
}

export type ListClaimsApiV1ClaimsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listClaimsApiV1ClaimsGet>>>
export type ListClaimsApiV1ClaimsGetQueryError = AxiosError<HTTPValidationError>


/**
 * @summary List Claims
 */

export function useListClaimsApiV1ClaimsGet<TData = Awaited<ReturnType<typeof listClaimsApiV1ClaimsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: MaybeRef<ListClaimsApiV1ClaimsGetParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClaimsApiV1ClaimsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListClaimsApiV1ClaimsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




/**
 * Create a new claim and optionally link it to references.
 * @summary Create Claim
 */
export const createClaimApiV1ClaimsPost = (
    claimCreate: MaybeRef<ClaimCreate>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ClaimOut>> => {
    claimCreate = unref(claimCreate);
    
    return axios.default.post(
      `/api/v1/claims/`,
      claimCreate,options
    );
  }



export const getCreateClaimApiV1ClaimsPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createClaimApiV1ClaimsPost>>, TError,{data: ClaimCreate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createClaimApiV1ClaimsPost>>, TError,{data: ClaimCreate}, TContext> => {

const mutationKey = ['createClaimApiV1ClaimsPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createClaimApiV1ClaimsPost>>, {data: ClaimCreate}> = (props) => {
          const {data} = props ?? {};

          return  createClaimApiV1ClaimsPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateClaimApiV1ClaimsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createClaimApiV1ClaimsPost>>>
    export type CreateClaimApiV1ClaimsPostMutationBody = ClaimCreate
    export type CreateClaimApiV1ClaimsPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Create Claim
 */
export const useCreateClaimApiV1ClaimsPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createClaimApiV1ClaimsPost>>, TError,{data: ClaimCreate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createClaimApiV1ClaimsPost>>,
        TError,
        {data: ClaimCreate},
        TContext
      > => {

      const mutationOptions = getCreateClaimApiV1ClaimsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get a claim with full reference details.
 * @summary Get Claim
 */
export const getClaimApiV1ClaimsClaimIdGet = (
    claimId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ClaimWithReferences>> => {
    claimId = unref(claimId);
    
    return axios.default.get(
      `/api/v1/claims/${claimId}`,options
    );
  }




export const getGetClaimApiV1ClaimsClaimIdGetQueryKey = (claimId?: MaybeRef<number>,) => {
    return [
    'api','v1','claims',claimId
    ] as const;
    }

    
export const getGetClaimApiV1ClaimsClaimIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getClaimApiV1ClaimsClaimIdGet>>, TError = AxiosError<HTTPValidationError>>(claimId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClaimApiV1ClaimsClaimIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getGetClaimApiV1ClaimsClaimIdGetQueryKey(claimId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClaimApiV1ClaimsClaimIdGet>>> = ({ signal }) => getClaimApiV1ClaimsClaimIdGet(claimId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(claimId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClaimApiV1ClaimsClaimIdGet>>, TError, TData> 
}

export type GetClaimApiV1ClaimsClaimIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getClaimApiV1ClaimsClaimIdGet>>>
export type GetClaimApiV1ClaimsClaimIdGetQueryError = AxiosError<HTTPValidationError>


/**
 * @summary Get Claim
 */

export function useGetClaimApiV1ClaimsClaimIdGet<TData = Awaited<ReturnType<typeof getClaimApiV1ClaimsClaimIdGet>>, TError = AxiosError<HTTPValidationError>>(
 claimId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClaimApiV1ClaimsClaimIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetClaimApiV1ClaimsClaimIdGetQueryOptions(claimId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




/**
 * Update a claim.
 * @summary Update Claim
 */
export const updateClaimApiV1ClaimsClaimIdPut = (
    claimId: MaybeRef<number>,
    claimUpdate: MaybeRef<ClaimUpdate>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ClaimOut>> => {
    claimId = unref(claimId);
claimUpdate = unref(claimUpdate);
    
    return axios.default.put(
      `/api/v1/claims/${claimId}`,
      claimUpdate,options
    );
  }



export const getUpdateClaimApiV1ClaimsClaimIdPutMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateClaimApiV1ClaimsClaimIdPut>>, TError,{claimId: number;data: ClaimUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateClaimApiV1ClaimsClaimIdPut>>, TError,{claimId: number;data: ClaimUpdate}, TContext> => {

const mutationKey = ['updateClaimApiV1ClaimsClaimIdPut'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateClaimApiV1ClaimsClaimIdPut>>, {claimId: number;data: ClaimUpdate}> = (props) => {
          const {claimId,data} = props ?? {};

          return  updateClaimApiV1ClaimsClaimIdPut(claimId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateClaimApiV1ClaimsClaimIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateClaimApiV1ClaimsClaimIdPut>>>
    export type UpdateClaimApiV1ClaimsClaimIdPutMutationBody = ClaimUpdate
    export type UpdateClaimApiV1ClaimsClaimIdPutMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Update Claim
 */
export const useUpdateClaimApiV1ClaimsClaimIdPut = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateClaimApiV1ClaimsClaimIdPut>>, TError,{claimId: number;data: ClaimUpdate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateClaimApiV1ClaimsClaimIdPut>>,
        TError,
        {claimId: number;data: ClaimUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateClaimApiV1ClaimsClaimIdPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a claim.
 * @summary Delete Claim
 */
export const deleteClaimApiV1ClaimsClaimIdDelete = (
    claimId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    claimId = unref(claimId);
    
    return axios.default.delete(
      `/api/v1/claims/${claimId}`,options
    );
  }



export const getDeleteClaimApiV1ClaimsClaimIdDeleteMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteClaimApiV1ClaimsClaimIdDelete>>, TError,{claimId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteClaimApiV1ClaimsClaimIdDelete>>, TError,{claimId: number}, TContext> => {

const mutationKey = ['deleteClaimApiV1ClaimsClaimIdDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteClaimApiV1ClaimsClaimIdDelete>>, {claimId: number}> = (props) => {
          const {claimId} = props ?? {};

          return  deleteClaimApiV1ClaimsClaimIdDelete(claimId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteClaimApiV1ClaimsClaimIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteClaimApiV1ClaimsClaimIdDelete>>>
    
    export type DeleteClaimApiV1ClaimsClaimIdDeleteMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Delete Claim
 */
export const useDeleteClaimApiV1ClaimsClaimIdDelete = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteClaimApiV1ClaimsClaimIdDelete>>, TError,{claimId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteClaimApiV1ClaimsClaimIdDelete>>,
        TError,
        {claimId: number},
        TContext
      > => {

      const mutationOptions = getDeleteClaimApiV1ClaimsClaimIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Link a claim to a reference.
 * @summary Link Claim To Reference
 */
export const linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPost = (
    claimId: MaybeRef<number>,
    referenceId: MaybeRef<number>,
    params?: MaybeRef<LinkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostParams>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ClaimOut>> => {
    claimId = unref(claimId);
referenceId = unref(referenceId);
params = unref(params);
    
    return axios.default.post(
      `/api/v1/claims/${claimId}/references/${referenceId}`,undefined,{
    ...options,
        params: {...unref(params), ...options?.params},}
    );
  }



export const getLinkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPost>>, TError,{claimId: number;referenceId: number;params?: LinkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPost>>, TError,{claimId: number;referenceId: number;params?: LinkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostParams}, TContext> => {

const mutationKey = ['linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPost>>, {claimId: number;referenceId: number;params?: LinkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostParams}> = (props) => {
          const {claimId,referenceId,params} = props ?? {};

          return  linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPost(claimId,referenceId,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LinkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostMutationResult = NonNullable<Awaited<ReturnType<typeof linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPost>>>
    
    export type LinkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Link Claim To Reference
 */
export const useLinkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPost>>, TError,{claimId: number;referenceId: number;params?: LinkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPost>>,
        TError,
        {claimId: number;referenceId: number;params?: LinkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostParams},
        TContext
      > => {

      const mutationOptions = getLinkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Unlink a claim from a reference.
 * @summary Unlink Claim From Reference
 */
export const unlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDelete = (
    claimId: MaybeRef<number>,
    referenceId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    claimId = unref(claimId);
referenceId = unref(referenceId);
    
    return axios.default.delete(
      `/api/v1/claims/${claimId}/references/${referenceId}`,options
    );
  }



export const getUnlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDeleteMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDelete>>, TError,{claimId: number;referenceId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof unlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDelete>>, TError,{claimId: number;referenceId: number}, TContext> => {

const mutationKey = ['unlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDelete>>, {claimId: number;referenceId: number}> = (props) => {
          const {claimId,referenceId} = props ?? {};

          return  unlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDelete(claimId,referenceId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof unlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDelete>>>
    
    export type UnlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDeleteMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Unlink Claim From Reference
 */
export const useUnlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDelete = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDelete>>, TError,{claimId: number;referenceId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof unlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDelete>>,
        TError,
        {claimId: number;referenceId: number},
        TContext
      > => {

      const mutationOptions = getUnlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    