/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  DocumentOut,
  HTTPValidationError
} from '../models';






/**
 * Retrieve a document by ID.

Args:
    document_id: Document ID
    session: Database session

Returns:
    Document with markdown content
 * @summary Get Document
 */
export const getDocumentApiV1DocumentsDocumentIdGet = (
    documentId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentOut>> => {
    documentId = unref(documentId);
    
    return axios.default.get(
      `/api/v1/documents/${documentId}`,options
    );
  }




export const getGetDocumentApiV1DocumentsDocumentIdGetQueryKey = (documentId?: MaybeRef<number>,) => {
    return [
    'api','v1','documents',documentId
    ] as const;
    }

    
export const getGetDocumentApiV1DocumentsDocumentIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentApiV1DocumentsDocumentIdGet>>, TError = AxiosError<HTTPValidationError>>(documentId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentApiV1DocumentsDocumentIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getGetDocumentApiV1DocumentsDocumentIdGetQueryKey(documentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentApiV1DocumentsDocumentIdGet>>> = ({ signal }) => getDocumentApiV1DocumentsDocumentIdGet(documentId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(documentId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentApiV1DocumentsDocumentIdGet>>, TError, TData> 
}

export type GetDocumentApiV1DocumentsDocumentIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentApiV1DocumentsDocumentIdGet>>>
export type GetDocumentApiV1DocumentsDocumentIdGetQueryError = AxiosError<HTTPValidationError>


/**
 * @summary Get Document
 */

export function useGetDocumentApiV1DocumentsDocumentIdGet<TData = Awaited<ReturnType<typeof getDocumentApiV1DocumentsDocumentIdGet>>, TError = AxiosError<HTTPValidationError>>(
 documentId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentApiV1DocumentsDocumentIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetDocumentApiV1DocumentsDocumentIdGetQueryOptions(documentId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




/**
 * Delete a document by ID.

Args:
    document_id: Document ID
    session: Database session

Returns:
    Success message
 * @summary Delete Document
 */
export const deleteDocumentApiV1DocumentsDocumentIdDelete = (
    documentId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    documentId = unref(documentId);
    
    return axios.default.delete(
      `/api/v1/documents/${documentId}`,options
    );
  }



export const getDeleteDocumentApiV1DocumentsDocumentIdDeleteMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentApiV1DocumentsDocumentIdDelete>>, TError,{documentId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentApiV1DocumentsDocumentIdDelete>>, TError,{documentId: number}, TContext> => {

const mutationKey = ['deleteDocumentApiV1DocumentsDocumentIdDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDocumentApiV1DocumentsDocumentIdDelete>>, {documentId: number}> = (props) => {
          const {documentId} = props ?? {};

          return  deleteDocumentApiV1DocumentsDocumentIdDelete(documentId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDocumentApiV1DocumentsDocumentIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDocumentApiV1DocumentsDocumentIdDelete>>>
    
    export type DeleteDocumentApiV1DocumentsDocumentIdDeleteMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Delete Document
 */
export const useDeleteDocumentApiV1DocumentsDocumentIdDelete = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentApiV1DocumentsDocumentIdDelete>>, TError,{documentId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteDocumentApiV1DocumentsDocumentIdDelete>>,
        TError,
        {documentId: number},
        TContext
      > => {

      const mutationOptions = getDeleteDocumentApiV1DocumentsDocumentIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve all documents for a project.

Args:
    project_id: Project ID
    session: Database session

Returns:
    List of documents for the project
 * @summary Get Project Documents
 */
export const getProjectDocumentsApiV1DocumentsProjectProjectIdGet = (
    projectId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentOut[]>> => {
    projectId = unref(projectId);
    
    return axios.default.get(
      `/api/v1/documents/project/${projectId}`,options
    );
  }




export const getGetProjectDocumentsApiV1DocumentsProjectProjectIdGetQueryKey = (projectId?: MaybeRef<number>,) => {
    return [
    'api','v1','documents','project',projectId
    ] as const;
    }

    
export const getGetProjectDocumentsApiV1DocumentsProjectProjectIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getProjectDocumentsApiV1DocumentsProjectProjectIdGet>>, TError = AxiosError<HTTPValidationError>>(projectId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectDocumentsApiV1DocumentsProjectProjectIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getGetProjectDocumentsApiV1DocumentsProjectProjectIdGetQueryKey(projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectDocumentsApiV1DocumentsProjectProjectIdGet>>> = ({ signal }) => getProjectDocumentsApiV1DocumentsProjectProjectIdGet(projectId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(projectId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjectDocumentsApiV1DocumentsProjectProjectIdGet>>, TError, TData> 
}

export type GetProjectDocumentsApiV1DocumentsProjectProjectIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectDocumentsApiV1DocumentsProjectProjectIdGet>>>
export type GetProjectDocumentsApiV1DocumentsProjectProjectIdGetQueryError = AxiosError<HTTPValidationError>


/**
 * @summary Get Project Documents
 */

export function useGetProjectDocumentsApiV1DocumentsProjectProjectIdGet<TData = Awaited<ReturnType<typeof getProjectDocumentsApiV1DocumentsProjectProjectIdGet>>, TError = AxiosError<HTTPValidationError>>(
 projectId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectDocumentsApiV1DocumentsProjectProjectIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetProjectDocumentsApiV1DocumentsProjectProjectIdGetQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




