/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  DocumentOut,
  HTTPValidationError
} from '../models';






/**
 * Retrieve a document by ID.

Args:
    document_id: Document ID
    session: Database session

Returns:
    Document with markdown content
 * @summary Get Document
 */
export const getDocument = (
    documentId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentOut>> => {
    documentId = unref(documentId);
    
    return axios.default.get(
      `/api/v1/documents/${documentId}`,options
    );
  }




export const getGetDocumentQueryKey = (documentId?: MaybeRef<number>,) => {
    return [
    'api','v1','documents',documentId
    ] as const;
    }

    
export const getGetDocumentQueryOptions = <TData = Awaited<ReturnType<typeof getDocument>>, TError = AxiosError<HTTPValidationError>>(documentId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getGetDocumentQueryKey(documentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocument>>> = ({ signal }) => getDocument(documentId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(documentId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData> 
}

export type GetDocumentQueryResult = NonNullable<Awaited<ReturnType<typeof getDocument>>>
export type GetDocumentQueryError = AxiosError<HTTPValidationError>


/**
 * @summary Get Document
 */

export function useGetDocument<TData = Awaited<ReturnType<typeof getDocument>>, TError = AxiosError<HTTPValidationError>>(
 documentId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetDocumentQueryOptions(documentId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




/**
 * Delete a document by ID.

Args:
    document_id: Document ID
    session: Database session

Returns:
    Success message
 * @summary Delete Document
 */
export const deleteDocument = (
    documentId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    documentId = unref(documentId);
    
    return axios.default.delete(
      `/api/v1/documents/${documentId}`,options
    );
  }



export const getDeleteDocumentMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocument>>, TError,{documentId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDocument>>, TError,{documentId: number}, TContext> => {

const mutationKey = ['deleteDocument'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDocument>>, {documentId: number}> = (props) => {
          const {documentId} = props ?? {};

          return  deleteDocument(documentId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDocument>>>
    
    export type DeleteDocumentMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Delete Document
 */
export const useDeleteDocument = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocument>>, TError,{documentId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteDocument>>,
        TError,
        {documentId: number},
        TContext
      > => {

      const mutationOptions = getDeleteDocumentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve all documents for a project.

Args:
    project_id: Project ID
    session: Database session

Returns:
    List of documents for the project
 * @summary Get Project Documents
 */
export const listProjectDocuments = (
    projectId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentOut[]>> => {
    projectId = unref(projectId);
    
    return axios.default.get(
      `/api/v1/documents/project/${projectId}`,options
    );
  }




export const getListProjectDocumentsQueryKey = (projectId?: MaybeRef<number>,) => {
    return [
    'api','v1','documents','project',projectId
    ] as const;
    }

    
export const getListProjectDocumentsQueryOptions = <TData = Awaited<ReturnType<typeof listProjectDocuments>>, TError = AxiosError<HTTPValidationError>>(projectId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjectDocuments>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getListProjectDocumentsQueryKey(projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProjectDocuments>>> = ({ signal }) => listProjectDocuments(projectId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(projectId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProjectDocuments>>, TError, TData> 
}

export type ListProjectDocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof listProjectDocuments>>>
export type ListProjectDocumentsQueryError = AxiosError<HTTPValidationError>


/**
 * @summary Get Project Documents
 */

export function useListProjectDocuments<TData = Awaited<ReturnType<typeof listProjectDocuments>>, TError = AxiosError<HTTPValidationError>>(
 projectId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjectDocuments>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListProjectDocumentsQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




