/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  HTTPValidationError,
  ListProjectsApiV1ProjectsGetParams,
  PaginatedResponseProjectOut,
  ProjectCreate,
  ProjectOut,
  ProjectUpdate
} from '../models';






/**
 * @summary List Projects
 */
export const listProjectsApiV1ProjectsGet = (
    params?: MaybeRef<ListProjectsApiV1ProjectsGetParams>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedResponseProjectOut>> => {
    params = unref(params);
    
    return axios.default.get(
      `/api/v1/projects/`,{
    ...options,
        params: {...unref(params), ...options?.params},}
    );
  }




export const getListProjectsApiV1ProjectsGetQueryKey = (params?: MaybeRef<ListProjectsApiV1ProjectsGetParams>,) => {
    return [
    'api','v1','projects', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListProjectsApiV1ProjectsGetQueryOptions = <TData = Awaited<ReturnType<typeof listProjectsApiV1ProjectsGet>>, TError = AxiosError<HTTPValidationError>>(params?: MaybeRef<ListProjectsApiV1ProjectsGetParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjectsApiV1ProjectsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getListProjectsApiV1ProjectsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProjectsApiV1ProjectsGet>>> = ({ signal }) => listProjectsApiV1ProjectsGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProjectsApiV1ProjectsGet>>, TError, TData> 
}

export type ListProjectsApiV1ProjectsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listProjectsApiV1ProjectsGet>>>
export type ListProjectsApiV1ProjectsGetQueryError = AxiosError<HTTPValidationError>


/**
 * @summary List Projects
 */

export function useListProjectsApiV1ProjectsGet<TData = Awaited<ReturnType<typeof listProjectsApiV1ProjectsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: MaybeRef<ListProjectsApiV1ProjectsGetParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjectsApiV1ProjectsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListProjectsApiV1ProjectsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




/**
 * @summary Create Project
 */
export const createProjectApiV1ProjectsPost = (
    projectCreate: MaybeRef<ProjectCreate>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectOut>> => {
    projectCreate = unref(projectCreate);
    
    return axios.default.post(
      `/api/v1/projects/`,
      projectCreate,options
    );
  }



export const getCreateProjectApiV1ProjectsPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProjectApiV1ProjectsPost>>, TError,{data: ProjectCreate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createProjectApiV1ProjectsPost>>, TError,{data: ProjectCreate}, TContext> => {

const mutationKey = ['createProjectApiV1ProjectsPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProjectApiV1ProjectsPost>>, {data: ProjectCreate}> = (props) => {
          const {data} = props ?? {};

          return  createProjectApiV1ProjectsPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProjectApiV1ProjectsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createProjectApiV1ProjectsPost>>>
    export type CreateProjectApiV1ProjectsPostMutationBody = ProjectCreate
    export type CreateProjectApiV1ProjectsPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Create Project
 */
export const useCreateProjectApiV1ProjectsPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProjectApiV1ProjectsPost>>, TError,{data: ProjectCreate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createProjectApiV1ProjectsPost>>,
        TError,
        {data: ProjectCreate},
        TContext
      > => {

      const mutationOptions = getCreateProjectApiV1ProjectsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Project
 */
export const getProjectApiV1ProjectsProjectIdGet = (
    projectId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectOut>> => {
    projectId = unref(projectId);
    
    return axios.default.get(
      `/api/v1/projects/${projectId}`,options
    );
  }




export const getGetProjectApiV1ProjectsProjectIdGetQueryKey = (projectId?: MaybeRef<number>,) => {
    return [
    'api','v1','projects',projectId
    ] as const;
    }

    
export const getGetProjectApiV1ProjectsProjectIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getProjectApiV1ProjectsProjectIdGet>>, TError = AxiosError<HTTPValidationError>>(projectId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectApiV1ProjectsProjectIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getGetProjectApiV1ProjectsProjectIdGetQueryKey(projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectApiV1ProjectsProjectIdGet>>> = ({ signal }) => getProjectApiV1ProjectsProjectIdGet(projectId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(projectId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjectApiV1ProjectsProjectIdGet>>, TError, TData> 
}

export type GetProjectApiV1ProjectsProjectIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectApiV1ProjectsProjectIdGet>>>
export type GetProjectApiV1ProjectsProjectIdGetQueryError = AxiosError<HTTPValidationError>


/**
 * @summary Get Project
 */

export function useGetProjectApiV1ProjectsProjectIdGet<TData = Awaited<ReturnType<typeof getProjectApiV1ProjectsProjectIdGet>>, TError = AxiosError<HTTPValidationError>>(
 projectId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectApiV1ProjectsProjectIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetProjectApiV1ProjectsProjectIdGetQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




/**
 * @summary Update Project
 */
export const updateProjectApiV1ProjectsProjectIdPut = (
    projectId: MaybeRef<number>,
    projectUpdate: MaybeRef<ProjectUpdate>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectOut>> => {
    projectId = unref(projectId);
projectUpdate = unref(projectUpdate);
    
    return axios.default.put(
      `/api/v1/projects/${projectId}`,
      projectUpdate,options
    );
  }



export const getUpdateProjectApiV1ProjectsProjectIdPutMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProjectApiV1ProjectsProjectIdPut>>, TError,{projectId: number;data: ProjectUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateProjectApiV1ProjectsProjectIdPut>>, TError,{projectId: number;data: ProjectUpdate}, TContext> => {

const mutationKey = ['updateProjectApiV1ProjectsProjectIdPut'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProjectApiV1ProjectsProjectIdPut>>, {projectId: number;data: ProjectUpdate}> = (props) => {
          const {projectId,data} = props ?? {};

          return  updateProjectApiV1ProjectsProjectIdPut(projectId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProjectApiV1ProjectsProjectIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateProjectApiV1ProjectsProjectIdPut>>>
    export type UpdateProjectApiV1ProjectsProjectIdPutMutationBody = ProjectUpdate
    export type UpdateProjectApiV1ProjectsProjectIdPutMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Update Project
 */
export const useUpdateProjectApiV1ProjectsProjectIdPut = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProjectApiV1ProjectsProjectIdPut>>, TError,{projectId: number;data: ProjectUpdate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateProjectApiV1ProjectsProjectIdPut>>,
        TError,
        {projectId: number;data: ProjectUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateProjectApiV1ProjectsProjectIdPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Project
 */
export const deleteProjectApiV1ProjectsProjectIdDelete = (
    projectId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    projectId = unref(projectId);
    
    return axios.default.delete(
      `/api/v1/projects/${projectId}`,options
    );
  }



export const getDeleteProjectApiV1ProjectsProjectIdDeleteMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProjectApiV1ProjectsProjectIdDelete>>, TError,{projectId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProjectApiV1ProjectsProjectIdDelete>>, TError,{projectId: number}, TContext> => {

const mutationKey = ['deleteProjectApiV1ProjectsProjectIdDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProjectApiV1ProjectsProjectIdDelete>>, {projectId: number}> = (props) => {
          const {projectId} = props ?? {};

          return  deleteProjectApiV1ProjectsProjectIdDelete(projectId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProjectApiV1ProjectsProjectIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProjectApiV1ProjectsProjectIdDelete>>>
    
    export type DeleteProjectApiV1ProjectsProjectIdDeleteMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Delete Project
 */
export const useDeleteProjectApiV1ProjectsProjectIdDelete = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProjectApiV1ProjectsProjectIdDelete>>, TError,{projectId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteProjectApiV1ProjectsProjectIdDelete>>,
        TError,
        {projectId: number},
        TContext
      > => {

      const mutationOptions = getDeleteProjectApiV1ProjectsProjectIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    