/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  HTTPValidationError,
  ListReferencesApiV1ReferencesGetParams,
  PaginatedResponseReferenceOut,
  ReferenceCreate,
  ReferenceOut,
  ReferenceUpdate
} from '../models';






/**
 * List all references with pagination.
 * @summary List References
 */
export const listReferencesApiV1ReferencesGet = (
    params?: MaybeRef<ListReferencesApiV1ReferencesGetParams>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedResponseReferenceOut>> => {
    params = unref(params);
    
    return axios.default.get(
      `/api/v1/references/`,{
    ...options,
        params: {...unref(params), ...options?.params},}
    );
  }




export const getListReferencesApiV1ReferencesGetQueryKey = (params?: MaybeRef<ListReferencesApiV1ReferencesGetParams>,) => {
    return [
    'api','v1','references', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListReferencesApiV1ReferencesGetQueryOptions = <TData = Awaited<ReturnType<typeof listReferencesApiV1ReferencesGet>>, TError = AxiosError<HTTPValidationError>>(params?: MaybeRef<ListReferencesApiV1ReferencesGetParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReferencesApiV1ReferencesGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getListReferencesApiV1ReferencesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listReferencesApiV1ReferencesGet>>> = ({ signal }) => listReferencesApiV1ReferencesGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listReferencesApiV1ReferencesGet>>, TError, TData> 
}

export type ListReferencesApiV1ReferencesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listReferencesApiV1ReferencesGet>>>
export type ListReferencesApiV1ReferencesGetQueryError = AxiosError<HTTPValidationError>


/**
 * @summary List References
 */

export function useListReferencesApiV1ReferencesGet<TData = Awaited<ReturnType<typeof listReferencesApiV1ReferencesGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: MaybeRef<ListReferencesApiV1ReferencesGetParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReferencesApiV1ReferencesGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListReferencesApiV1ReferencesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




/**
 * Create a new reference or return existing if duplicate found.

Deduplication strategy:
1. Compute dedup_hash from DOI (if available) or title+first_author
2. Check if reference with same hash exists
3. If exists, return existing reference
4. Otherwise, create new reference
 * @summary Create Reference
 */
export const createReferenceApiV1ReferencesPost = (
    referenceCreate: MaybeRef<ReferenceCreate>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReferenceOut>> => {
    referenceCreate = unref(referenceCreate);
    
    return axios.default.post(
      `/api/v1/references/`,
      referenceCreate,options
    );
  }



export const getCreateReferenceApiV1ReferencesPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReferenceApiV1ReferencesPost>>, TError,{data: ReferenceCreate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createReferenceApiV1ReferencesPost>>, TError,{data: ReferenceCreate}, TContext> => {

const mutationKey = ['createReferenceApiV1ReferencesPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReferenceApiV1ReferencesPost>>, {data: ReferenceCreate}> = (props) => {
          const {data} = props ?? {};

          return  createReferenceApiV1ReferencesPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateReferenceApiV1ReferencesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createReferenceApiV1ReferencesPost>>>
    export type CreateReferenceApiV1ReferencesPostMutationBody = ReferenceCreate
    export type CreateReferenceApiV1ReferencesPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Create Reference
 */
export const useCreateReferenceApiV1ReferencesPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReferenceApiV1ReferencesPost>>, TError,{data: ReferenceCreate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createReferenceApiV1ReferencesPost>>,
        TError,
        {data: ReferenceCreate},
        TContext
      > => {

      const mutationOptions = getCreateReferenceApiV1ReferencesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get a specific reference by ID.
 * @summary Get Reference
 */
export const getReferenceApiV1ReferencesReferenceIdGet = (
    referenceId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReferenceOut>> => {
    referenceId = unref(referenceId);
    
    return axios.default.get(
      `/api/v1/references/${referenceId}`,options
    );
  }




export const getGetReferenceApiV1ReferencesReferenceIdGetQueryKey = (referenceId?: MaybeRef<number>,) => {
    return [
    'api','v1','references',referenceId
    ] as const;
    }

    
export const getGetReferenceApiV1ReferencesReferenceIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getReferenceApiV1ReferencesReferenceIdGet>>, TError = AxiosError<HTTPValidationError>>(referenceId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferenceApiV1ReferencesReferenceIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getGetReferenceApiV1ReferencesReferenceIdGetQueryKey(referenceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferenceApiV1ReferencesReferenceIdGet>>> = ({ signal }) => getReferenceApiV1ReferencesReferenceIdGet(referenceId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(referenceId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferenceApiV1ReferencesReferenceIdGet>>, TError, TData> 
}

export type GetReferenceApiV1ReferencesReferenceIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getReferenceApiV1ReferencesReferenceIdGet>>>
export type GetReferenceApiV1ReferencesReferenceIdGetQueryError = AxiosError<HTTPValidationError>


/**
 * @summary Get Reference
 */

export function useGetReferenceApiV1ReferencesReferenceIdGet<TData = Awaited<ReturnType<typeof getReferenceApiV1ReferencesReferenceIdGet>>, TError = AxiosError<HTTPValidationError>>(
 referenceId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferenceApiV1ReferencesReferenceIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetReferenceApiV1ReferencesReferenceIdGetQueryOptions(referenceId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




/**
 * Update a reference.
 * @summary Update Reference
 */
export const updateReferenceApiV1ReferencesReferenceIdPut = (
    referenceId: MaybeRef<number>,
    referenceUpdate: MaybeRef<ReferenceUpdate>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReferenceOut>> => {
    referenceId = unref(referenceId);
referenceUpdate = unref(referenceUpdate);
    
    return axios.default.put(
      `/api/v1/references/${referenceId}`,
      referenceUpdate,options
    );
  }



export const getUpdateReferenceApiV1ReferencesReferenceIdPutMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReferenceApiV1ReferencesReferenceIdPut>>, TError,{referenceId: number;data: ReferenceUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateReferenceApiV1ReferencesReferenceIdPut>>, TError,{referenceId: number;data: ReferenceUpdate}, TContext> => {

const mutationKey = ['updateReferenceApiV1ReferencesReferenceIdPut'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateReferenceApiV1ReferencesReferenceIdPut>>, {referenceId: number;data: ReferenceUpdate}> = (props) => {
          const {referenceId,data} = props ?? {};

          return  updateReferenceApiV1ReferencesReferenceIdPut(referenceId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateReferenceApiV1ReferencesReferenceIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateReferenceApiV1ReferencesReferenceIdPut>>>
    export type UpdateReferenceApiV1ReferencesReferenceIdPutMutationBody = ReferenceUpdate
    export type UpdateReferenceApiV1ReferencesReferenceIdPutMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Update Reference
 */
export const useUpdateReferenceApiV1ReferencesReferenceIdPut = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReferenceApiV1ReferencesReferenceIdPut>>, TError,{referenceId: number;data: ReferenceUpdate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateReferenceApiV1ReferencesReferenceIdPut>>,
        TError,
        {referenceId: number;data: ReferenceUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateReferenceApiV1ReferencesReferenceIdPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a reference.
 * @summary Delete Reference
 */
export const deleteReferenceApiV1ReferencesReferenceIdDelete = (
    referenceId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    referenceId = unref(referenceId);
    
    return axios.default.delete(
      `/api/v1/references/${referenceId}`,options
    );
  }



export const getDeleteReferenceApiV1ReferencesReferenceIdDeleteMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferenceApiV1ReferencesReferenceIdDelete>>, TError,{referenceId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReferenceApiV1ReferencesReferenceIdDelete>>, TError,{referenceId: number}, TContext> => {

const mutationKey = ['deleteReferenceApiV1ReferencesReferenceIdDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReferenceApiV1ReferencesReferenceIdDelete>>, {referenceId: number}> = (props) => {
          const {referenceId} = props ?? {};

          return  deleteReferenceApiV1ReferencesReferenceIdDelete(referenceId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteReferenceApiV1ReferencesReferenceIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReferenceApiV1ReferencesReferenceIdDelete>>>
    
    export type DeleteReferenceApiV1ReferencesReferenceIdDeleteMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Delete Reference
 */
export const useDeleteReferenceApiV1ReferencesReferenceIdDelete = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferenceApiV1ReferencesReferenceIdDelete>>, TError,{referenceId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteReferenceApiV1ReferencesReferenceIdDelete>>,
        TError,
        {referenceId: number},
        TContext
      > => {

      const mutationOptions = getDeleteReferenceApiV1ReferencesReferenceIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Bulk create references with automatic deduplication.

Returns list of reference IDs (existing or newly created).
 * @summary Bulk Create References
 */
export const bulkCreateReferencesApiV1ReferencesBulkPost = (
    referenceCreate: MaybeRef<ReferenceCreate[]>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReferenceOut[]>> => {
    referenceCreate = unref(referenceCreate);
    
    return axios.default.post(
      `/api/v1/references/bulk`,
      referenceCreate,options
    );
  }



export const getBulkCreateReferencesApiV1ReferencesBulkPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkCreateReferencesApiV1ReferencesBulkPost>>, TError,{data: ReferenceCreate[]}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof bulkCreateReferencesApiV1ReferencesBulkPost>>, TError,{data: ReferenceCreate[]}, TContext> => {

const mutationKey = ['bulkCreateReferencesApiV1ReferencesBulkPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bulkCreateReferencesApiV1ReferencesBulkPost>>, {data: ReferenceCreate[]}> = (props) => {
          const {data} = props ?? {};

          return  bulkCreateReferencesApiV1ReferencesBulkPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BulkCreateReferencesApiV1ReferencesBulkPostMutationResult = NonNullable<Awaited<ReturnType<typeof bulkCreateReferencesApiV1ReferencesBulkPost>>>
    export type BulkCreateReferencesApiV1ReferencesBulkPostMutationBody = ReferenceCreate[]
    export type BulkCreateReferencesApiV1ReferencesBulkPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Bulk Create References
 */
export const useBulkCreateReferencesApiV1ReferencesBulkPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkCreateReferencesApiV1ReferencesBulkPost>>, TError,{data: ReferenceCreate[]}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof bulkCreateReferencesApiV1ReferencesBulkPost>>,
        TError,
        {data: ReferenceCreate[]},
        TContext
      > => {

      const mutationOptions = getBulkCreateReferencesApiV1ReferencesBulkPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    