/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  HTTPValidationError,
  ListReferencesParams,
  PaginatedResponseReferenceOut,
  ReferenceCreate,
  ReferenceOut,
  ReferenceUpdate
} from '../models';






/**
 * List all references with pagination.
 * @summary List References
 */
export const listReferences = (
    params?: MaybeRef<ListReferencesParams>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedResponseReferenceOut>> => {
    params = unref(params);
    
    return axios.default.get(
      `/api/v1/references/`,{
    ...options,
        params: {...unref(params), ...options?.params},}
    );
  }




export const getListReferencesQueryKey = (params?: MaybeRef<ListReferencesParams>,) => {
    return [
    'api','v1','references', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListReferencesQueryOptions = <TData = Awaited<ReturnType<typeof listReferences>>, TError = AxiosError<HTTPValidationError>>(params?: MaybeRef<ListReferencesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReferences>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getListReferencesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listReferences>>> = ({ signal }) => listReferences(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listReferences>>, TError, TData> 
}

export type ListReferencesQueryResult = NonNullable<Awaited<ReturnType<typeof listReferences>>>
export type ListReferencesQueryError = AxiosError<HTTPValidationError>


/**
 * @summary List References
 */

export function useListReferences<TData = Awaited<ReturnType<typeof listReferences>>, TError = AxiosError<HTTPValidationError>>(
 params?: MaybeRef<ListReferencesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReferences>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListReferencesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




/**
 * Create a new reference or return existing if duplicate found.

Deduplication strategy:
1. Compute dedup_hash from DOI (if available) or title+first_author
2. Check if reference with same hash exists
3. If exists, return existing reference
4. Otherwise, create new reference
 * @summary Create Reference
 */
export const createReference = (
    referenceCreate: MaybeRef<ReferenceCreate>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReferenceOut>> => {
    referenceCreate = unref(referenceCreate);
    
    return axios.default.post(
      `/api/v1/references/`,
      referenceCreate,options
    );
  }



export const getCreateReferenceMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReference>>, TError,{data: ReferenceCreate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createReference>>, TError,{data: ReferenceCreate}, TContext> => {

const mutationKey = ['createReference'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReference>>, {data: ReferenceCreate}> = (props) => {
          const {data} = props ?? {};

          return  createReference(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateReferenceMutationResult = NonNullable<Awaited<ReturnType<typeof createReference>>>
    export type CreateReferenceMutationBody = ReferenceCreate
    export type CreateReferenceMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Create Reference
 */
export const useCreateReference = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReference>>, TError,{data: ReferenceCreate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createReference>>,
        TError,
        {data: ReferenceCreate},
        TContext
      > => {

      const mutationOptions = getCreateReferenceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get a specific reference by ID.
 * @summary Get Reference
 */
export const getReference = (
    referenceId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReferenceOut>> => {
    referenceId = unref(referenceId);
    
    return axios.default.get(
      `/api/v1/references/${referenceId}`,options
    );
  }




export const getGetReferenceQueryKey = (referenceId?: MaybeRef<number>,) => {
    return [
    'api','v1','references',referenceId
    ] as const;
    }

    
export const getGetReferenceQueryOptions = <TData = Awaited<ReturnType<typeof getReference>>, TError = AxiosError<HTTPValidationError>>(referenceId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReference>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getGetReferenceQueryKey(referenceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReference>>> = ({ signal }) => getReference(referenceId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(referenceId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReference>>, TError, TData> 
}

export type GetReferenceQueryResult = NonNullable<Awaited<ReturnType<typeof getReference>>>
export type GetReferenceQueryError = AxiosError<HTTPValidationError>


/**
 * @summary Get Reference
 */

export function useGetReference<TData = Awaited<ReturnType<typeof getReference>>, TError = AxiosError<HTTPValidationError>>(
 referenceId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReference>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetReferenceQueryOptions(referenceId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}




/**
 * Update a reference.
 * @summary Update Reference
 */
export const updateReference = (
    referenceId: MaybeRef<number>,
    referenceUpdate: MaybeRef<ReferenceUpdate>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReferenceOut>> => {
    referenceId = unref(referenceId);
referenceUpdate = unref(referenceUpdate);
    
    return axios.default.put(
      `/api/v1/references/${referenceId}`,
      referenceUpdate,options
    );
  }



export const getUpdateReferenceMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReference>>, TError,{referenceId: number;data: ReferenceUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateReference>>, TError,{referenceId: number;data: ReferenceUpdate}, TContext> => {

const mutationKey = ['updateReference'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateReference>>, {referenceId: number;data: ReferenceUpdate}> = (props) => {
          const {referenceId,data} = props ?? {};

          return  updateReference(referenceId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateReferenceMutationResult = NonNullable<Awaited<ReturnType<typeof updateReference>>>
    export type UpdateReferenceMutationBody = ReferenceUpdate
    export type UpdateReferenceMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Update Reference
 */
export const useUpdateReference = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReference>>, TError,{referenceId: number;data: ReferenceUpdate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateReference>>,
        TError,
        {referenceId: number;data: ReferenceUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateReferenceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a reference.
 * @summary Delete Reference
 */
export const deleteReference = (
    referenceId: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    referenceId = unref(referenceId);
    
    return axios.default.delete(
      `/api/v1/references/${referenceId}`,options
    );
  }



export const getDeleteReferenceMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReference>>, TError,{referenceId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReference>>, TError,{referenceId: number}, TContext> => {

const mutationKey = ['deleteReference'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReference>>, {referenceId: number}> = (props) => {
          const {referenceId} = props ?? {};

          return  deleteReference(referenceId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteReferenceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReference>>>
    
    export type DeleteReferenceMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Delete Reference
 */
export const useDeleteReference = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReference>>, TError,{referenceId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteReference>>,
        TError,
        {referenceId: number},
        TContext
      > => {

      const mutationOptions = getDeleteReferenceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Bulk create references with automatic deduplication.

Returns list of reference IDs (existing or newly created).
 * @summary Bulk Create References
 */
export const bulkCreateReferences = (
    referenceCreate: MaybeRef<ReferenceCreate[]>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReferenceOut[]>> => {
    referenceCreate = unref(referenceCreate);
    
    return axios.default.post(
      `/api/v1/references/bulk`,
      referenceCreate,options
    );
  }



export const getBulkCreateReferencesMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkCreateReferences>>, TError,{data: ReferenceCreate[]}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof bulkCreateReferences>>, TError,{data: ReferenceCreate[]}, TContext> => {

const mutationKey = ['bulkCreateReferences'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bulkCreateReferences>>, {data: ReferenceCreate[]}> = (props) => {
          const {data} = props ?? {};

          return  bulkCreateReferences(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BulkCreateReferencesMutationResult = NonNullable<Awaited<ReturnType<typeof bulkCreateReferences>>>
    export type BulkCreateReferencesMutationBody = ReferenceCreate[]
    export type BulkCreateReferencesMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Bulk Create References
 */
export const useBulkCreateReferences = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkCreateReferences>>, TError,{data: ReferenceCreate[]}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof bulkCreateReferences>>,
        TError,
        {data: ReferenceCreate[]},
        TContext
      > => {

      const mutationOptions = getBulkCreateReferencesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    