/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';



/**
 * List claims with optional filtering by project.
 * @summary List Claims
 */
export const listClaimsApiV1ClaimsGetQueryPageDefault = 1;

export const listClaimsApiV1ClaimsGetQueryPageSizeDefault = 20;
export const listClaimsApiV1ClaimsGetQueryPageSizeMax = 100;



export const listClaimsApiV1ClaimsGetQueryParams = zod.object({
  "project_id": zod.union([zod.number(),zod.null()]).optional().describe('Filter by project ID'),
  "page": zod.number().min(1).default(listClaimsApiV1ClaimsGetQueryPageDefault).describe('Page number (1-indexed)'),
  "page_size": zod.number().min(1).max(listClaimsApiV1ClaimsGetQueryPageSizeMax).default(listClaimsApiV1ClaimsGetQueryPageSizeDefault).describe('Items per page')
})

export const listClaimsApiV1ClaimsGetResponseDataItemReferencesDefault = [];

export const listClaimsApiV1ClaimsGetResponse = zod.object({
  "data": zod.array(zod.object({
  "text": zod.string(),
  "claim_type": zod.union([zod.string(),zod.null()]).optional(),
  "page_number": zod.union([zod.number(),zod.null()]).optional(),
  "paragraph_index": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.number(),
  "project_id": zod.number(),
  "verification_status": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "references": zod.array(zod.number()).default(listClaimsApiV1ClaimsGetResponseDataItemReferencesDefault)
}).describe('Schema for claim output')).describe('List of items'),
  "total": zod.number().describe('Total number of items'),
  "page": zod.number().describe('Current page number (1-indexed)'),
  "page_size": zod.number().describe('Number of items per page'),
  "total_pages": zod.number().describe('Total number of pages')
})

/**
 * Create a new claim and optionally link it to references.
 * @summary Create Claim
 */
export const createClaimApiV1ClaimsPostBodyReferenceIdsDefault = [];

export const createClaimApiV1ClaimsPostBody = zod.object({
  "text": zod.string(),
  "claim_type": zod.union([zod.string(),zod.null()]).optional(),
  "page_number": zod.union([zod.number(),zod.null()]).optional(),
  "paragraph_index": zod.union([zod.number(),zod.null()]).optional(),
  "project_id": zod.number(),
  "reference_ids": zod.array(zod.number()).default(createClaimApiV1ClaimsPostBodyReferenceIdsDefault)
}).describe('Schema for creating a claim')

/**
 * Get a claim with full reference details.
 * @summary Get Claim
 */
export const getClaimApiV1ClaimsClaimIdGetParams = zod.object({
  "claim_id": zod.number()
})

export const getClaimApiV1ClaimsClaimIdGetResponseReferencesDefault = [];export const getClaimApiV1ClaimsClaimIdGetResponseReferenceDetailsDefault = [];

export const getClaimApiV1ClaimsClaimIdGetResponse = zod.object({
  "text": zod.string(),
  "claim_type": zod.union([zod.string(),zod.null()]).optional(),
  "page_number": zod.union([zod.number(),zod.null()]).optional(),
  "paragraph_index": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.number(),
  "project_id": zod.number(),
  "verification_status": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "references": zod.array(zod.number()).default(getClaimApiV1ClaimsClaimIdGetResponseReferencesDefault),
  "reference_details": zod.array(zod.object({
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "title": zod.string(),
  "authors": zod.string(),
  "source": zod.union([zod.string(),zod.null()]).optional(),
  "year": zod.union([zod.number(),zod.null()]).optional(),
  "url": zod.union([zod.string(),zod.null()]).optional(),
  "id": zod.number(),
  "dedup_hash": zod.string(),
  "is_processed": zod.boolean(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('Schema for reference output')).default(getClaimApiV1ClaimsClaimIdGetResponseReferenceDetailsDefault)
}).describe('Schema for claim with full reference details')

/**
 * Update a claim.
 * @summary Update Claim
 */
export const updateClaimApiV1ClaimsClaimIdPutParams = zod.object({
  "claim_id": zod.number()
})

export const updateClaimApiV1ClaimsClaimIdPutBody = zod.object({
  "text": zod.union([zod.string(),zod.null()]).optional(),
  "claim_type": zod.union([zod.string(),zod.null()]).optional(),
  "page_number": zod.union([zod.number(),zod.null()]).optional(),
  "paragraph_index": zod.union([zod.number(),zod.null()]).optional(),
  "verification_status": zod.union([zod.string(),zod.null()]).optional()
}).describe('Schema for updating a claim')

export const updateClaimApiV1ClaimsClaimIdPutResponseReferencesDefault = [];

export const updateClaimApiV1ClaimsClaimIdPutResponse = zod.object({
  "text": zod.string(),
  "claim_type": zod.union([zod.string(),zod.null()]).optional(),
  "page_number": zod.union([zod.number(),zod.null()]).optional(),
  "paragraph_index": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.number(),
  "project_id": zod.number(),
  "verification_status": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "references": zod.array(zod.number()).default(updateClaimApiV1ClaimsClaimIdPutResponseReferencesDefault)
}).describe('Schema for claim output')

/**
 * Delete a claim.
 * @summary Delete Claim
 */
export const deleteClaimApiV1ClaimsClaimIdDeleteParams = zod.object({
  "claim_id": zod.number()
})

/**
 * Link a claim to a reference.
 * @summary Link Claim To Reference
 */
export const linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostParams = zod.object({
  "claim_id": zod.number(),
  "reference_id": zod.number()
})

export const linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostQueryRelevanceScoreMinOne = 0;
export const linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostQueryRelevanceScoreMaxOne = 1;



export const linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostQueryParams = zod.object({
  "relevance_score": zod.union([zod.number().min(linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostQueryRelevanceScoreMinOne).max(linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostQueryRelevanceScoreMaxOne),zod.null()]).optional(),
  "context": zod.union([zod.string(),zod.null()]).optional()
})

export const linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostResponseReferencesDefault = [];

export const linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostResponse = zod.object({
  "text": zod.string(),
  "claim_type": zod.union([zod.string(),zod.null()]).optional(),
  "page_number": zod.union([zod.number(),zod.null()]).optional(),
  "paragraph_index": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.number(),
  "project_id": zod.number(),
  "verification_status": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "references": zod.array(zod.number()).default(linkClaimToReferenceApiV1ClaimsClaimIdReferencesReferenceIdPostResponseReferencesDefault)
}).describe('Schema for claim output')

/**
 * Unlink a claim from a reference.
 * @summary Unlink Claim From Reference
 */
export const unlinkClaimFromReferenceApiV1ClaimsClaimIdReferencesReferenceIdDeleteParams = zod.object({
  "claim_id": zod.number(),
  "reference_id": zod.number()
})

