/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';



/**
 * List claims with optional filtering by project.
 * @summary List Claims
 */
export const listClaimsQueryPageDefault = 1;

export const listClaimsQueryPageSizeDefault = 20;
export const listClaimsQueryPageSizeMax = 100;



export const listClaimsQueryParams = zod.object({
  "project_id": zod.union([zod.number(),zod.null()]).optional().describe('Filter by project ID'),
  "page": zod.number().min(1).default(listClaimsQueryPageDefault).describe('Page number (1-indexed)'),
  "page_size": zod.number().min(1).max(listClaimsQueryPageSizeMax).default(listClaimsQueryPageSizeDefault).describe('Items per page')
})

export const listClaimsResponseDataItemReferencesDefault = [];

export const listClaimsResponse = zod.object({
  "data": zod.array(zod.object({
  "text": zod.string(),
  "claim_type": zod.union([zod.string(),zod.null()]).optional(),
  "page_number": zod.union([zod.number(),zod.null()]).optional(),
  "paragraph_index": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.number(),
  "project_id": zod.number(),
  "verification_status": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "references": zod.array(zod.number()).default(listClaimsResponseDataItemReferencesDefault)
}).describe('Schema for claim output')).describe('List of items'),
  "total": zod.number().describe('Total number of items'),
  "page": zod.number().describe('Current page number (1-indexed)'),
  "page_size": zod.number().describe('Number of items per page'),
  "total_pages": zod.number().describe('Total number of pages')
})

/**
 * Create a new claim and optionally link it to references.
 * @summary Create Claim
 */
export const createClaimBodyReferenceIdsDefault = [];

export const createClaimBody = zod.object({
  "text": zod.string(),
  "claim_type": zod.union([zod.string(),zod.null()]).optional(),
  "page_number": zod.union([zod.number(),zod.null()]).optional(),
  "paragraph_index": zod.union([zod.number(),zod.null()]).optional(),
  "project_id": zod.number(),
  "reference_ids": zod.array(zod.number()).default(createClaimBodyReferenceIdsDefault)
}).describe('Schema for creating a claim')

/**
 * Get a claim with full reference details.
 * @summary Get Claim
 */
export const getClaimParams = zod.object({
  "claim_id": zod.number()
})

export const getClaimResponseReferencesDefault = [];export const getClaimResponseReferenceDetailsDefault = [];

export const getClaimResponse = zod.object({
  "text": zod.string(),
  "claim_type": zod.union([zod.string(),zod.null()]).optional(),
  "page_number": zod.union([zod.number(),zod.null()]).optional(),
  "paragraph_index": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.number(),
  "project_id": zod.number(),
  "verification_status": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "references": zod.array(zod.number()).default(getClaimResponseReferencesDefault),
  "reference_details": zod.array(zod.object({
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "title": zod.string(),
  "authors": zod.string(),
  "source": zod.union([zod.string(),zod.null()]).optional(),
  "year": zod.union([zod.number(),zod.null()]).optional(),
  "url": zod.union([zod.string(),zod.null()]).optional(),
  "id": zod.number(),
  "dedup_hash": zod.string(),
  "is_processed": zod.boolean(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('Schema for reference output')).default(getClaimResponseReferenceDetailsDefault)
}).describe('Schema for claim with full reference details')

/**
 * Update a claim.
 * @summary Update Claim
 */
export const updateClaimParams = zod.object({
  "claim_id": zod.number()
})

export const updateClaimBody = zod.object({
  "text": zod.union([zod.string(),zod.null()]).optional(),
  "claim_type": zod.union([zod.string(),zod.null()]).optional(),
  "page_number": zod.union([zod.number(),zod.null()]).optional(),
  "paragraph_index": zod.union([zod.number(),zod.null()]).optional(),
  "verification_status": zod.union([zod.string(),zod.null()]).optional()
}).describe('Schema for updating a claim')

export const updateClaimResponseReferencesDefault = [];

export const updateClaimResponse = zod.object({
  "text": zod.string(),
  "claim_type": zod.union([zod.string(),zod.null()]).optional(),
  "page_number": zod.union([zod.number(),zod.null()]).optional(),
  "paragraph_index": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.number(),
  "project_id": zod.number(),
  "verification_status": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "references": zod.array(zod.number()).default(updateClaimResponseReferencesDefault)
}).describe('Schema for claim output')

/**
 * Delete a claim.
 * @summary Delete Claim
 */
export const deleteClaimParams = zod.object({
  "claim_id": zod.number()
})

/**
 * Link a claim to a reference.
 * @summary Link Claim To Reference
 */
export const linkClaimToReferenceParams = zod.object({
  "claim_id": zod.number(),
  "reference_id": zod.number()
})

export const linkClaimToReferenceQueryRelevanceScoreMinOne = 0;
export const linkClaimToReferenceQueryRelevanceScoreMaxOne = 1;



export const linkClaimToReferenceQueryParams = zod.object({
  "relevance_score": zod.union([zod.number().min(linkClaimToReferenceQueryRelevanceScoreMinOne).max(linkClaimToReferenceQueryRelevanceScoreMaxOne),zod.null()]).optional(),
  "context": zod.union([zod.string(),zod.null()]).optional()
})

export const linkClaimToReferenceResponseReferencesDefault = [];

export const linkClaimToReferenceResponse = zod.object({
  "text": zod.string(),
  "claim_type": zod.union([zod.string(),zod.null()]).optional(),
  "page_number": zod.union([zod.number(),zod.null()]).optional(),
  "paragraph_index": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.number(),
  "project_id": zod.number(),
  "verification_status": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "references": zod.array(zod.number()).default(linkClaimToReferenceResponseReferencesDefault)
}).describe('Schema for claim output')

/**
 * Unlink a claim from a reference.
 * @summary Unlink Claim From Reference
 */
export const unlinkClaimFromReferenceParams = zod.object({
  "claim_id": zod.number(),
  "reference_id": zod.number()
})

