/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';



/**
 * Retrieve a document by ID.

Args:
    document_id: Document ID
    session: Database session

Returns:
    Document with markdown content
 * @summary Get Document
 */
export const getDocumentParams = zod.object({
  "document_id": zod.number()
})

export const getDocumentResponse = zod.object({
  "filename": zod.string(),
  "document_title": zod.union([zod.string(),zod.null()]).optional(),
  "markdown_content": zod.string(),
  "page_count": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.number(),
  "project_id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

/**
 * Delete a document by ID.

Args:
    document_id: Document ID
    session: Database session

Returns:
    Success message
 * @summary Delete Document
 */
export const deleteDocumentParams = zod.object({
  "document_id": zod.number()
})

export const deleteDocumentResponse = zod.unknown()

/**
 * Retrieve all documents for a project.

Args:
    project_id: Project ID
    session: Database session

Returns:
    List of documents for the project
 * @summary Get Project Documents
 */
export const listProjectDocumentsParams = zod.object({
  "project_id": zod.number()
})

export const listProjectDocumentsResponseItem = zod.object({
  "filename": zod.string(),
  "document_title": zod.union([zod.string(),zod.null()]).optional(),
  "markdown_content": zod.string(),
  "page_count": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.number(),
  "project_id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})
export const listProjectDocumentsResponse = zod.array(listProjectDocumentsResponseItem)

