/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';



/**
 * Process PDF document and extract markdown.

This endpoint:
1. Converts PDF to clean Markdown format using Docling
2. Stores the markdown in the database for later RAG processing
3. Returns the markdown for viewing and manual reference selection

Args:
    project_id: Project ID to associate the document with
    file: PDF file upload
    session: Database session

Returns:
    Document ID and markdown content
 * @summary Process Pdf
 */
export const processPdfQueryParams = zod.object({
  "project_id": zod.number()
})

export const processPdfBody = zod.object({
  "file": zod.instanceof(File)
})

export const processPdfResponse = zod.object({
  "project_id": zod.number(),
  "document_id": zod.number(),
  "filename": zod.string(),
  "document_title": zod.union([zod.string(),zod.null()]),
  "markdown": zod.string(),
  "page_count": zod.union([zod.number(),zod.null()])
}).describe('Schema for PDF to Markdown conversion response.')

/**
 * Extract claims and references from text using LM Studio.

This endpoint:
1. Uses LLM to extract claims and references from the provided text
2. Deduplicates references against existing database entries
3. Creates new claims linked to the project
4. Links claims to their supporting references

Args:
    request: Text extraction request with text and project_id
    session: Database session

Returns:
    Extraction response with statistics
 * @summary Process Text
 */
export const extractClaimsAndReferencesBody = zod.object({
  "text": zod.string().describe('Text to extract claims and references from'),
  "project_id": zod.number().describe('Project ID to associate the extracted claims with')
}).describe('Schema for text extraction request.')

export const extractClaimsAndReferencesResponse = zod.object({
  "project_id": zod.number(),
  "extraction_result": zod.object({
  "claims": zod.array(zod.object({
  "text": zod.string().describe('The claim text'),
  "claim_type": zod.union([zod.string(),zod.null()]).optional().describe('Type of claim (factual, statistical, opinion, etc.)'),
  "page_number": zod.union([zod.number(),zod.null()]).optional().describe('Page number where claim appears'),
  "paragraph_index": zod.union([zod.number(),zod.null()]).optional().describe('Paragraph index'),
  "reference_indices": zod.array(zod.number()).optional().describe('Indices of references that support this claim (0-based index into the references list)')
}).describe('Schema for an extracted claim from text.')).optional().describe('Extracted claims'),
  "references": zod.array(zod.object({
  "title": zod.string().describe('Title of the reference'),
  "authors": zod.string().describe('Authors of the reference (comma-separated or formatted)'),
  "year": zod.union([zod.number(),zod.null()]).optional().describe('Publication year'),
  "source": zod.union([zod.string(),zod.null()]).optional().describe('Source (journal, conference, book, etc.)'),
  "doi": zod.union([zod.string(),zod.null()]).optional().describe('DOI if available'),
  "url": zod.union([zod.string(),zod.null()]).optional().describe('URL if available')
}).describe('Schema for an extracted reference from text.')).optional().describe('Extracted references')
}).describe('Schema for the complete extraction result.'),
  "claims_created": zod.number(),
  "references_created": zod.number(),
  "references_deduplicated": zod.number()
}).describe('Schema for text extraction response.')

/**
 * Extract only references from text using LM Studio.

This endpoint:
1. Uses LLM to extract references from the provided text
2. Deduplicates references against existing database entries
3. Creates new reference records

Args:
    request: References extraction request with text and project_id
    session: Database session

Returns:
    Extraction response with statistics
 * @summary Process References
 */
export const extractReferencesBody = zod.object({
  "text": zod.string().describe('Text to extract references from'),
  "project_id": zod.number().describe('Project ID to associate the extracted references with')
}).describe('Schema for references-only extraction request.')

export const extractReferencesResponse = zod.object({
  "project_id": zod.number(),
  "references": zod.array(zod.object({
  "title": zod.string().describe('Title of the reference'),
  "authors": zod.string().describe('Authors of the reference (comma-separated or formatted)'),
  "year": zod.union([zod.number(),zod.null()]).optional().describe('Publication year'),
  "source": zod.union([zod.string(),zod.null()]).optional().describe('Source (journal, conference, book, etc.)'),
  "doi": zod.union([zod.string(),zod.null()]).optional().describe('DOI if available'),
  "url": zod.union([zod.string(),zod.null()]).optional().describe('URL if available')
}).describe('Schema for an extracted reference from text.')),
  "references_created": zod.number(),
  "references_deduplicated": zod.number()
}).describe('Schema for references-only extraction response.')

