/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';



/**
 * @summary List Projects
 */
export const listProjectsQueryPageDefault = 1;

export const listProjectsQueryPageSizeDefault = 20;
export const listProjectsQueryPageSizeMax = 100;



export const listProjectsQueryParams = zod.object({
  "page": zod.number().min(1).default(listProjectsQueryPageDefault).describe('Page number (1-indexed)'),
  "page_size": zod.number().min(1).max(listProjectsQueryPageSizeMax).default(listProjectsQueryPageSizeDefault).describe('Items per page')
})

export const listProjectsResponseDataItemStatusDefault = "draft";

export const listProjectsResponse = zod.object({
  "data": zod.array(zod.object({
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.union([zod.enum(['draft', 'processing', 'ready']),zod.null()]).default(listProjectsResponseDataItemStatusDefault),
  "id": zod.number(),
  "document_path": zod.union([zod.string(),zod.null()]).optional(),
  "document_filename": zod.union([zod.string(),zod.null()]).optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})).describe('List of items'),
  "total": zod.number().describe('Total number of items'),
  "page": zod.number().describe('Current page number (1-indexed)'),
  "page_size": zod.number().describe('Number of items per page'),
  "total_pages": zod.number().describe('Total number of pages')
})

/**
 * @summary Create Project
 */
export const createProjectBodyStatusDefault = "draft";

export const createProjectBody = zod.object({
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.union([zod.enum(['draft', 'processing', 'ready']),zod.null()]).default(createProjectBodyStatusDefault)
})

/**
 * @summary Get Project
 */
export const getProjectParams = zod.object({
  "project_id": zod.number()
})

export const getProjectResponseStatusDefault = "draft";

export const getProjectResponse = zod.object({
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.union([zod.enum(['draft', 'processing', 'ready']),zod.null()]).default(getProjectResponseStatusDefault),
  "id": zod.number(),
  "document_path": zod.union([zod.string(),zod.null()]).optional(),
  "document_filename": zod.union([zod.string(),zod.null()]).optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

/**
 * @summary Update Project
 */
export const updateProjectParams = zod.object({
  "project_id": zod.number()
})

export const updateProjectBody = zod.object({
  "name": zod.union([zod.string(),zod.null()]).optional(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.union([zod.enum(['draft', 'processing', 'ready']),zod.null()]).optional(),
  "document_path": zod.union([zod.string(),zod.null()]).optional(),
  "document_filename": zod.union([zod.string(),zod.null()]).optional()
})

export const updateProjectResponseStatusDefault = "draft";

export const updateProjectResponse = zod.object({
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.union([zod.enum(['draft', 'processing', 'ready']),zod.null()]).default(updateProjectResponseStatusDefault),
  "id": zod.number(),
  "document_path": zod.union([zod.string(),zod.null()]).optional(),
  "document_filename": zod.union([zod.string(),zod.null()]).optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

/**
 * @summary Delete Project
 */
export const deleteProjectParams = zod.object({
  "project_id": zod.number()
})

