/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';



/**
 * @summary List Projects
 */
export const listProjectsApiV1ProjectsGetQueryPageDefault = 1;

export const listProjectsApiV1ProjectsGetQueryPageSizeDefault = 20;
export const listProjectsApiV1ProjectsGetQueryPageSizeMax = 100;



export const listProjectsApiV1ProjectsGetQueryParams = zod.object({
  "page": zod.number().min(1).default(listProjectsApiV1ProjectsGetQueryPageDefault).describe('Page number (1-indexed)'),
  "page_size": zod.number().min(1).max(listProjectsApiV1ProjectsGetQueryPageSizeMax).default(listProjectsApiV1ProjectsGetQueryPageSizeDefault).describe('Items per page')
})

export const listProjectsApiV1ProjectsGetResponseDataItemStatusDefault = "draft";

export const listProjectsApiV1ProjectsGetResponse = zod.object({
  "data": zod.array(zod.object({
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.union([zod.enum(['draft', 'processing', 'ready']),zod.null()]).default(listProjectsApiV1ProjectsGetResponseDataItemStatusDefault),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})).describe('List of items'),
  "total": zod.number().describe('Total number of items'),
  "page": zod.number().describe('Current page number (1-indexed)'),
  "page_size": zod.number().describe('Number of items per page'),
  "total_pages": zod.number().describe('Total number of pages')
})

/**
 * @summary Create Project
 */
export const createProjectApiV1ProjectsPostBodyStatusDefault = "draft";

export const createProjectApiV1ProjectsPostBody = zod.object({
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.union([zod.enum(['draft', 'processing', 'ready']),zod.null()]).default(createProjectApiV1ProjectsPostBodyStatusDefault)
})

/**
 * @summary Get Project
 */
export const getProjectApiV1ProjectsProjectIdGetParams = zod.object({
  "project_id": zod.number()
})

export const getProjectApiV1ProjectsProjectIdGetResponseStatusDefault = "draft";

export const getProjectApiV1ProjectsProjectIdGetResponse = zod.object({
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.union([zod.enum(['draft', 'processing', 'ready']),zod.null()]).default(getProjectApiV1ProjectsProjectIdGetResponseStatusDefault),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

/**
 * @summary Update Project
 */
export const updateProjectApiV1ProjectsProjectIdPutParams = zod.object({
  "project_id": zod.number()
})

export const updateProjectApiV1ProjectsProjectIdPutBody = zod.object({
  "name": zod.union([zod.string(),zod.null()]).optional(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.union([zod.enum(['draft', 'processing', 'ready']),zod.null()]).optional()
})

export const updateProjectApiV1ProjectsProjectIdPutResponseStatusDefault = "draft";

export const updateProjectApiV1ProjectsProjectIdPutResponse = zod.object({
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.union([zod.enum(['draft', 'processing', 'ready']),zod.null()]).default(updateProjectApiV1ProjectsProjectIdPutResponseStatusDefault),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

/**
 * @summary Delete Project
 */
export const deleteProjectApiV1ProjectsProjectIdDeleteParams = zod.object({
  "project_id": zod.number()
})

