/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fastapi-Nuxt Template
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';



/**
 * List all references with pagination.
 * @summary List References
 */
export const listReferencesQueryPageDefault = 1;

export const listReferencesQueryPageSizeDefault = 20;
export const listReferencesQueryPageSizeMax = 100;



export const listReferencesQueryParams = zod.object({
  "page": zod.number().min(1).default(listReferencesQueryPageDefault).describe('Page number (1-indexed)'),
  "page_size": zod.number().min(1).max(listReferencesQueryPageSizeMax).default(listReferencesQueryPageSizeDefault).describe('Items per page')
})

export const listReferencesResponse = zod.object({
  "data": zod.array(zod.object({
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "title": zod.string(),
  "authors": zod.string(),
  "source": zod.union([zod.string(),zod.null()]).optional(),
  "year": zod.union([zod.number(),zod.null()]).optional(),
  "url": zod.union([zod.string(),zod.null()]).optional(),
  "id": zod.number(),
  "dedup_hash": zod.string(),
  "is_processed": zod.boolean(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('Schema for reference output')).describe('List of items'),
  "total": zod.number().describe('Total number of items'),
  "page": zod.number().describe('Current page number (1-indexed)'),
  "page_size": zod.number().describe('Number of items per page'),
  "total_pages": zod.number().describe('Total number of pages')
})

/**
 * Create a new reference or return existing if duplicate found.

Deduplication strategy:
1. Compute dedup_hash from DOI (if available) or title+first_author
2. Check if reference with same hash exists
3. If exists, return existing reference
4. Otherwise, create new reference
 * @summary Create Reference
 */
export const createReferenceBody = zod.object({
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "title": zod.string(),
  "authors": zod.string(),
  "source": zod.union([zod.string(),zod.null()]).optional(),
  "year": zod.union([zod.number(),zod.null()]).optional(),
  "url": zod.union([zod.string(),zod.null()]).optional()
}).describe('Schema for creating a reference')

/**
 * Get a specific reference by ID.
 * @summary Get Reference
 */
export const getReferenceParams = zod.object({
  "reference_id": zod.number()
})

export const getReferenceResponse = zod.object({
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "title": zod.string(),
  "authors": zod.string(),
  "source": zod.union([zod.string(),zod.null()]).optional(),
  "year": zod.union([zod.number(),zod.null()]).optional(),
  "url": zod.union([zod.string(),zod.null()]).optional(),
  "id": zod.number(),
  "dedup_hash": zod.string(),
  "is_processed": zod.boolean(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('Schema for reference output')

/**
 * Update a reference.
 * @summary Update Reference
 */
export const updateReferenceParams = zod.object({
  "reference_id": zod.number()
})

export const updateReferenceBody = zod.object({
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "title": zod.union([zod.string(),zod.null()]).optional(),
  "authors": zod.union([zod.string(),zod.null()]).optional(),
  "source": zod.union([zod.string(),zod.null()]).optional(),
  "year": zod.union([zod.number(),zod.null()]).optional(),
  "url": zod.union([zod.string(),zod.null()]).optional(),
  "is_processed": zod.union([zod.boolean(),zod.null()]).optional()
}).describe('Schema for updating a reference')

export const updateReferenceResponse = zod.object({
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "title": zod.string(),
  "authors": zod.string(),
  "source": zod.union([zod.string(),zod.null()]).optional(),
  "year": zod.union([zod.number(),zod.null()]).optional(),
  "url": zod.union([zod.string(),zod.null()]).optional(),
  "id": zod.number(),
  "dedup_hash": zod.string(),
  "is_processed": zod.boolean(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('Schema for reference output')

/**
 * Delete a reference.
 * @summary Delete Reference
 */
export const deleteReferenceParams = zod.object({
  "reference_id": zod.number()
})

/**
 * Bulk create references with automatic deduplication.

Returns list of reference IDs (existing or newly created).
 * @summary Bulk Create References
 */
export const bulkCreateReferencesBodyItem = zod.object({
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "title": zod.string(),
  "authors": zod.string(),
  "source": zod.union([zod.string(),zod.null()]).optional(),
  "year": zod.union([zod.number(),zod.null()]).optional(),
  "url": zod.union([zod.string(),zod.null()]).optional()
}).describe('Schema for creating a reference')
export const bulkCreateReferencesBody = zod.array(bulkCreateReferencesBodyItem)

export const bulkCreateReferencesResponseItem = zod.object({
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "title": zod.string(),
  "authors": zod.string(),
  "source": zod.union([zod.string(),zod.null()]).optional(),
  "year": zod.union([zod.number(),zod.null()]).optional(),
  "url": zod.union([zod.string(),zod.null()]).optional(),
  "id": zod.number(),
  "dedup_hash": zod.string(),
  "is_processed": zod.boolean(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('Schema for reference output')
export const bulkCreateReferencesResponse = zod.array(bulkCreateReferencesResponseItem)

